# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceUser',
            fields=[
                ('username', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DispatcherUser',
            fields=[
                ('username', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianUser',
            fields=[
                ('username', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('technician_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='technician.Technician')),
            ],
        ),
    ]
