# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 22:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('block_number', models.SmallIntegerField()),
                ('mobile_number', models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator('\\d{11}', 'Please enter a valid mobile number.')])),
                ('land_phone_number', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('\\d{8}', 'Please enter a valid phone number.')])),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_exprience', models.SmallIntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician.Skill')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician.Technician')),
            ],
        ),
    ]
