# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
