# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0003_auto_20160701_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
