# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerservice', '0001_initial'),
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PartName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=120)),
                ('quantity', models.SmallIntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ModelName')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_technician', models.CharField(blank=True, max_length=120)),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='technician.Technician')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True)),
                ('latitude', models.FloatField(blank=True)),
                ('date_of_visit', models.DateTimeField(blank=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('date_assigned', models.DateTimeField(blank=True, null=True)),
                ('date_solved', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('AS', 'Assigned'), ('WP', 'Work In Progress'), ('FL', 'Need Follow Up'), ('CL', 'Closed')], default='OP', max_length=10)),
                ('device_concerned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.Device')),
                ('technician_resposible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technician.Technician')),
            ],
        ),
        migrations.CreateModel(
            name='TicketSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('case_close_date', models.DateTimeField(auto_now_add=True)),
                ('problem_description', models.TextField(blank=True)),
                ('ticket_concerned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('technician_concerned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technician.Technician')),
                ('ticket_concerned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='visit_concerned',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.Visit'),
        ),
        migrations.AddField(
            model_name='actualpart',
            name='part_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.PartName'),
        ),
        migrations.AddField(
            model_name='actualpart',
            name='ticket_concerned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
    ]
