# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
